version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 6
    reviewers:
      - "marcduiker"

  - package-ecosystem: "nuget"
    directory: "/src/ServerlessPersistence"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 6
    reviewers:
      - "marcduiker"