# Blob Output tests

@baseUrl = http://localhost:7071/api
### String
POST {{baseUrl}}/StorePlayerWithStringBlobOutput
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Marc",
    "email" : "mduiker@xpirit.com"
}

### Stream
POST {{baseUrl}}/StorePlayerWithStreamBlobOutput
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Marc",
    "email" : "mduiker@xpirit.com"
}

### Dynamic Binding
POST {{baseUrl}}/StorePlayerWithStringBlobOutputDynamic
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Marc",
    "email" : "mduiker@xpirit.com"
}

### CloudBlockBlob
POST {{baseUrl}}/StorePlayerWithContainerBlobOutput
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Marc",
    "email" : "mduiker@xpirit.com"
}