# Blob input requests

@baseUrl = http://localhost:7071/api
@id1 = 470ef8af-27f9-469f-95a2-48b027e0ffff
### Stream
GET {{baseUrl}}/GetPlayerWithStreamBlobInput/{{id1}}

### Dynamic
@id2 = 4ce18929-7932-4c8b-bf1b-d6ca2b456fe7
GET {{baseUrl}}/GetPlayerWithStringBlobInputDynamic?id={{id2}}

### BlobList
GET {{baseUrl}}/GetBlobNamesWithContainerBlobInput