# Blob input requests
# Requires that json located in the tst/data folder are uploaded to the players/in/ container.
@baseUrl = http://localhost:7071/api
@id = 6bef5436-6106-42fa-9e37-eab36d0860d8
### Stream
GET {{baseUrl}}/GetPlayerWithStreamBlobInput/{{id}}

### Dynamic
@name = Margaret
GET {{baseUrl}}/GetPlayerWithStringBlobInputDynamic?name={{name}}
