# Table Input requests
@baseUrl = http://localhost:7071/api
@region = United States of America
@id = f547b999-931e-411e-85c9-e4eb8bc92f1a

### Get a single player by Id
GET {{baseUrl}}/GetPlayerByRegionAndIdTableInput/{{region}}/{{id}}

### Get multiple players by region
GET {{baseUrl}}/GetPlayersByRegionCloudTableInput?region={{region}}