# Table Input requests
@baseUrl = http://localhost:7071/api
@region = United States of America
@id = 21115d39-23e1-4a51-ac67-a68f06e98b2e

### Get a single player by Id
GET {{baseUrl}}/GetPlayerByRegionAndIdTableInput/{{region}}/{{id}}

### Get multiple players by region
GET {{baseUrl}}/GetPlayersByRegionCloudTableInput?region={{region}}